### ISSUE TITLE
M2 Macでrun_on_wasabi.shの実行がエラーになる

### ISSUE THREAD

**Issue by daaa1k** [d0iasm/sababook#1]
M2 Macでch0のrun_on_wasabi.shを実行したところ、添付のエラーになります。
エラー解消に向けて情報共有いただけますと幸いです。
[err.txt](https://github.com/user-attachments/files/17685329/err.txt)

以下は`rustup show`の実行結果です。

```
Default host: aarch64-apple-darwin
rustup home:  /Users/dd/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-2024-01-01-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-unknown-linux-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-2024-01-01-aarch64-apple-darwin (overridden by '/Users/dd/.../sababook/ch0/saba/rust-toolchain.toml')
rustc 1.77.0-nightly (e51e98dde 2023-12-31)
```

**Comment by daaa1k** [comment]
すみません、エラーメッセージにある通り、下記コマンドを実行すると成功しました。
`rustup target add x86_64-unknown-none`

**Comment by Teradad41** [comment]
M1 Mac でも同じように解決できました！

**Comment by d0iasm** [comment]
ありがとうございます。
筆者の環境では問題が再現しないため、現在調査中です。エラーログの添付もありがとうございます！

**Comment by hikalium** [comment]
こちらのサポートページにも書きましたが、さきほどOS側で修正を入れました！
一度自動でダウンロードされたMakefileを削除してから実行すれば、修正されたバージョンが反映されて、エラーは再現しなくなるはずです。
報告と解決案の提案、ありがとうございました！

https://lowlayergirls.github.io/wasabi-help/#the-x86_64-unknown-none-target-may-not-be-installed

**Comment by daaa1k** [comment]
迅速なご対応ありがとうございます！

**Comment by watarukura** [comment]
rustをbrewで入れているとcargoがこの辺に入っていて、uninstallしたらエラーがでなくなりました

```shell
❯ which cargo
/opt/homebrew/bin/cargo
```

`brew uninstall rust` の後

```shell
❯ which cargo
/Users/watarukura/.cargo/bin/cargo
```
