### ISSUE TITLE
run_on_wasabi.shを実行してもQEMUのGUIが立ち上がらない

### ISSUE THREAD

**Issue by daaa1k** [d0iasm/sababook#2]
`run_on_wasabi.sh`を実行してもQEMUのGUIが立ち上がりません。コンソールでsabaコマンドは実行できますが、書籍の図0-1にあるQEMUの画面が無い状態です。他に同じ症状の方は居ませんか？環境はM2 Mac (Sonoma 14.6.1)です。
`[ERROR] os/src/main.rs:147:  Failed("Timed out")`というエラーは出ていますが、それは図0-1にもあるので関係無いように思っています。
[log.txt](https://github.com/user-attachments/files/17686894/log.txt)

**Comment by daaa1k** [comment]
自己解決しました。
`export DISPLAY=0`
をスクリプト実行前に実行すると画面表示できました。
![スクリーンショット 2024-11-10 午前9 48 41](https://github.com/user-attachments/assets/e980e292-07d6-41a6-a0de-16d09f026b98)

おそらくMakefileの47行目でfalseになってしまい、vncの設定が入らないからだと思います。
![スクリーンショット 2024-11-10 午前9 58 42](https://github.com/user-attachments/assets/ee1eb9f0-56ca-4c43-8c27-f8df22789ce7)

**Comment by d0iasm** [comment]
issueの報告と解決策の発見までありがとうございます。とても助かります。OS側のビルドスクリプトの変更ができないか相談してみます。

**Comment by mpjpj742** [comment]
私も「run_on_wasabi.sh」で足踏みしています。
そもそもですが、この　run_on_wasabi.sh　をどこで実行すればいいのかわかりません。
私のPCはWindows11で、コマンド・プロンプトでやってみたり、PowerShellでやってみたり、MSYS2 UCRT64でやってみたり・・・。こんな初心者では、そもそもこの本の理解は無理なんでしょうか？
QEMUの画面は出てきません。ixページの「run_on_wasabi.sh スプリクトを使用してOS上でアプリケーションを動かしてみましょう」ということの意味が分かりません。

**Comment by d0iasm** [comment]
@mpjpj742 
コメントありがとうございます。
run_on_wasabi.shのスクリプトは、LinuxやMacのターミナルのアプリを使って実行することを想定しています。
Windowsですと、Windows Subsystem for Linux (WSL) というシステムを使い、擬似的にLinuxの環境を作ることでターミナルを使えるはずです。

このissueとは異なる問題なので、よければ新しくissueを作成してもらうことは可能でしょうか？そちらで続きのサポートをさせていただきます。

**Comment by mpjpj742** [comment]
ご返事ありがとうございます。
「新しくissueを作成する」とは、このページの右上の”+▼”（Open New…）のプルダウンメニューの中からどれかを選ぶのですか？New Repositoryでしょうか？

**Comment by d0iasm** [comment]
@mpjpj742 
New issue という緑色のボタンから新しいissueを報告できます。(添付の画像はスマホからなので、UIが少し異なるかもしれません)

![Image](https://github.com/user-attachments/assets/6f58f4dc-0dc2-4005-980b-94cf6c4a9045)

**Comment by ryohiy** [comment]
既にクローズ済みの issue に対してコメントすみません。私は別の方法で解決しましたので、一応共有させていただきます。

ただ、Cocoa を使うため恐らく mac 以外では解決しない可能性があり、https://github.com/d0iasm/sababook/issues/2#issuecomment-2466528747 の解決方法が適切に思いますので、そちらで対応するのが良いと思います。 あくまで共有までです。

Makefile の `QEMU_ARGS`に`-display cocoa \` のオプションをつける方法でもQEMUのGUI が立ち上がりました 🙏
